services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rockshop_inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rockshop_inventory_db"]
      interval: 5s
      retries: 5

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # The host name "db" resolves inside Docker’s network
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: rockshop_inventory_db
      DB_USER: postgres
      DB_PASSWORD: postgrespw
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

  # (nice extra) quick visual admin at http://localhost:8080
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: